```{r load_packages, message=FALSE}
library(dplyr)
library(tidyr)
library(coloc)
library(susieR)
```

```{r load_data}
gwas_sum_stats <- read_tsv("gwas_data.tsv")
qtl_sum_stats <- read_tsv("qtl_data.tsv")

```

```{r define_input_column_names}
# QTL
beta_qtl <- "BETA"
varbeta_qtl <- "VARBETA"
snp_qtl <- "VARIANT_ID"
gene_qtl <- "GENE"
chr_qtl <- "CHR"
position_qtl <- "POSITION"
sdY_qtl <- "SDY"

# GWAS
beta_gwas <- "beta"
varbeta_gwas <- "varbeta"
snp_gwas <- "snp"
chr_gwas <- "chr"
position_gwas <- "position"

```

```{r prepare_data}
# Define the minimum required sum stats data for QTL and GWAS
minimum_data_qtl <- c(beta_qtl, varbeta_qtl, snp_qtl, gene_qtl, chr_qtl, position_qtl, sdY_qtl)
minimum_data_gwas <- c(beta_gwas, varbeta_gwas, snp_gwas, chr_gwas, position_gwas)

# Check if the required columns are present in the QTL and GWAS data
if (!all(minimum_data_qtl %in% colnames(qtl_sum_stats))) {
  stop("QTL data is missing required columns: ", paste(setdiff(minimum_data_qtl, colnames(qtl_sum_stats)), collapse = ", "))
}

if (!all(minimum_data_gwas %in% colnames(gwas_sum_stats))) {
  stop("GWAS data is missing required columns: ", paste(setdiff(minimum_data_gwas, colnames(gwas_sum_stats)), collapse = ", "))
}

# Generate data set for coloc analysis
qtl_data <- qtl_sum_stats %>%
  select(all_of(minimum_data_qtl)) %>%
  rename(
    beta = !!beta_qtl,
    varbeta = !!varbeta_qtl,
    snp = !!snp_qtl,
    gene = !!gene_qtl,
    chr = !!chr_qtl,
    position = !!position_qtl,
    sdY = !!sdY_qtl
  ) %>%
  as.list()

gwas_data <- gwas_sum_stats %>%
  select(all_of(minimum_data_gwas)) %>%
  rename(
    beta = !!beta_gwas,
    varbeta = !!varbeta_gwas,
    snp = !!snp_gwas,
    chr = !!chr_gwas,
    position = !!position_gwas
  ) %>%
  as.list()

# Add type information for coloc
qtl_data$type <- "quant"
gwas_data$type <- "cc"

```

```{r run_susie}
# Run SuSiE
qtl_data_susie <- runsusie(qtl_data)
gwas_data_susie <- runsusie(gwas_data)

# Print Summary of SuSiE results
print("SuSiE Summary for QTL Data:\n")
print(summary(qtl_data_susie))

print("SuSiE Summary for GWAS Data:\n")
print(summary(gwas_data_susie))

```

```{r run_coloc}
# Run coloc.susie
coloc_results <- coloc.susie(qtl_data_susie, gwas_data_susie)

# Print Summary of coloc results
print("Coloc Results Summary:\n")
print(coloc_results$summary)
```

```{r sensitivity_analysis}
# Visualize the sensitivity of the coloc results


```